### ISSUE TITLE
Talk modélisation de donjon

### ISSUE THREAD

**Issue by gab-** [r3trofitted/talks#1]
Hè Ronan,
Salut !
J'aimerais beaucoup relire les slides de ton talk sur la (sur)modélisation de donjon, si tu es prêt à les partager.
En tout cas merci pour les fois où je t'ai écouté et toujours très apprécié !

Gabriel

**Comment by r3trofitted** [comment]
👍 Je vais essayer de les retrouver (les originaux sont sur papier et méritent un vrai coup de scanner plutôt que les photos prises vite fait dans le TGV…) et de les mettre ! Merci beaucoup pour tes gentil mots, ils me font très plaisir !

**Comment by r3trofitted** [comment]
C'est fait ! J'espère qu'ils te seront utiles, parce qu'ils sont très minimalistes !

**Comment by gab-** [comment]
Super, merci beaucoup !
